# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0002_auto_20180715_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('admin_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminDashboard.AdminProfile')),
            ],
        ),
    ]
