# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0003_adminreminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminreminder',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='trackemployee',
            options={'ordering': ['-report_date']},
        ),
    ]
