# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0004_auto_20180717_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackemployee',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='trackemployee',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='trackemployee',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='trackemployee',
            name='work_progress',
        ),
        migrations.RemoveField(
            model_name='trackemployee',
            name='work_title',
        ),
        migrations.DeleteModel(
            name='TrackEmployee',
        ),
    ]
