# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=50)),
                ('emp_name', models.CharField(max_length=30)),
                ('contact_no', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='profile_pics/employee/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_progress', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, default=None)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
