# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDashboard', '0003_auto_20180716_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportwork',
            name='emp_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmployeeDashboard.EmployeeProfile'),
        ),
    ]
